### ISSUE TITLE
Can i find mimic classes using javascript?

### ISSUE THREAD

**Issue by tatyshev** [peterchon/mimic#4]
It's great idea. But when i try to find classes like `col:1`, received following problems:

Firefox 40.0.3
<img width="439" alt="2015-09-11 13 19 47" src="https://cloud.githubusercontent.com/assets/2528926/9809169/d07a3a5e-5887-11e5-9b00-aa0e94bf236c.png">

Chrome 45
<img width="698" alt="2015-09-11 13 23 40" src="https://cloud.githubusercontent.com/assets/2528926/9809245/61da4cfa-5888-11e5-8c53-1651576786da.png">

But it's work when i use selector like `$('[class~="col:1"]')` :)

**Comment by peterchon** [comment]
you forgot the "." - if you use ".col:1" it should work.

**Comment by rathishcholarajan** [comment]
Just wanted to leave my comments on mimic w/o opening a new issue. I see myself using this for margin and padding. Beyond that I feel it clutters my HTML file. I find this more clear than using class names like margin-sm, margin-md or margin-lg.

**Comment by peterchon** [comment]
The basic for this practice was to show that you should be using a modular approach to CSS class naming. So that you can easily build it as a stacking component. I never really intended it as a framework, the files were available as a "see what you can do."

Anyhow, thanks for giving it a go - I'm working on a v2 that's going to hopefully address everyone's concern about the project.

**Comment by tatyshev** [comment]
@peterchon thank you.
I found a working variant for js selectors: `$(".col\\:1")` or `document.querySelector(".col\\:1")`

If you use `$(".col:1")` causes an error: 
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.col:1' is not a valid selector.
